const shopItems = [
    {
        drinkURL: "blueberry",
        drinkStatic: "/media/pudina_img.png",
        drinkGIF: "/media/tkc_pudina.gif",
        backgroundColor: "violet",
        backgroundURL: "berries",
        drinkName: "BLUEBERRY",
        drinkFullName: "BLUEBERRY LASSI",
        drinkCost: 19.99,
    }, {
        drinkURL: "punjabi",
        drinkStatic: "/media/pudina_img.png",
        drinkGIF: "/media/tkc_pudina.gif",
        backgroundColor: "white",
        backgroundURL: "berries",
        drinkName: "PUNJABI",
        drinkFullName: "CLASSIC PUNJABI LASSI",
        drinkCost: 19.99,
    }, {
        drinkURL: "gujarati",
        drinkStatic: "/media/pudina_img.png",
        drinkGIF: "/media/tkc_pudina.gif",
        backgroundColor: "yellow",
        backgroundURL: "spices",
        drinkName: "GUJARATI",
        drinkFullName: "GUJARATI CHAAS",
        drinkCost: 19.99,
    }, {
        drinkURL: "masala",
        drinkStatic: "/media/pudina_img.png",
        drinkGIF: "/media/tkc_pudina.gif",
        backgroundColor: "white",
        backgroundURL: "spices",
        drinkName: "MASALA",
        drinkFullName: "MASALA CHAAS",
        drinkCost: 19.99,
    }, {
        drinkURL: "peri_peri",
        drinkStatic: "/media/pudina_img.png",
        drinkGIF: "/media/tkc_pudina.gif",
        backgroundColor: "red",
        backgroundURL: "chilli",
        drinkName: "PERI-PERI",
        drinkFullName: "PERI-PERI CHAAS",
        drinkCost: 19.99,
    }, {
        drinkURL: "pudhina",
        drinkStatic: "/media/pudina_img.png",
        drinkGIF: "/media/tkc_pudina.gif",
        backgroundColor: "green",
        backgroundURL: "pudina",
        drinkName: "PUDINA",
        drinkFullName: "PUDINA SPICY CHAAS",
        drinkCost: 19.99,
    }, {
        drinkURL: "cookie_cream",
        drinkStatic: "/media/pudina_img.png",
        drinkGIF: "/media/tkc_pudina.gif",
        backgroundColor: "red",
        backgroundURL: "chilli",
        drinkName: "COOKIES",
        drinkFullName: "COOKIES AND DREAM LASSI",
        drinkCost: 19.99,
    }, {
        drinkURL: "mango",
        drinkStatic: "/media/pudina_img.png",
        drinkGIF: "/media/tkc_pudina.gif",
        backgroundColor: "yellow",
        backgroundURL: "aam",
        drinkName: "MANGO",
        drinkFullName: "MANGO LASSI",
        drinkCost: 19.99,
    }, {
        drinkURL: "rose",
        drinkStatic: "/media/pudina_img.png",
        drinkGIF: "/media/tkc_pudina.gif",
        backgroundColor: "baby-pink",
        backgroundURL: "rose_flower",
        drinkName: "ROSE",
        drinkFullName: "ROSE LASSI",
        drinkCost: 19.99,
    }
];

export {
    shopItems,
};